namespace MangaHub.Web.API.DTOs;

public sealed record MangaEntryResponse(
    Guid Id,
    string Title,
    string Authors,
    string CatalogCategory,
    string Description,
    string CoverUrl,
    string OpenLibraryKey,
    int? FirstPublishYear,
    string MetadataSource,
    string MyAnimeListId,
    string MediaType,
    string PublishingStatus,
    int? ChapterCount,
    int? VolumeCount,
    string ReadingStatus,
    string MangaDexId,
    decimal? MangaDexLatestChapter,
    DateTimeOffset? MangaDexLastSyncedAt,
    string MangaUpdatesId,
    decimal? MangaUpdatesLatestChapter,
    string MangaUpdatesStatus,
    bool? MangaUpdatesCompleted,
    DateTimeOffset? MangaUpdatesLastSyncedAt,
    Guid? LocalSeriesId,
    string CurrentChapter,
    int? Score,
    string Category,
    string Summary,
    string Notes,
    string FallbackReaderUrl,
    string ReaderPreference = "mangahub",
    decimal? MangaDexPreferredLanguageLatestChapter = null,
    bool IsRead = false,
    bool IsManualReleaseCheckDue = false,
    DateTimeOffset? LastExternalReaderVerifiedAt = null);

public sealed record ExternalReaderCheckInResponse(
    Guid MangaEntryId,
    string Title,
    string CurrentChapter,
    string FallbackReaderUrl,
    DateTimeOffset OpenedAt);

public sealed record ShelfSectionSummaryResponse(
    int Updates,
    int NewReleases,
    int Untracked,
    int Planned,
    int Reading,
    int Paused,
    int Done,
    int Dropped,
    int All);
