namespace MangaHub.Web.API.DTOs;

public sealed record MangaEntryResponse(
    Guid Id,
    string Title,
    string Authors,
    string CatalogCategory,
    string Description,
    string CoverUrl,
    string OpenLibraryKey,
    int? FirstPublishYear,
    string MetadataSource,
    string MyAnimeListId,
    string MediaType,
    string PublishingStatus,
    int? ChapterCount,
    int? VolumeCount,
    string ReadingStatus,
    string MangaDexUrl,
    string MangaDexId,
    DateTimeOffset? MangaDexLastSyncedAt,
    Guid? LocalSeriesId,
    string CurrentChapter,
    int? Score,
    string Category,
    string Summary,
    string Notes);
